### ISSUE TITLE
New package name?

### ISSUE THREAD

**Issue by jonashaag** [solsticedhiver/atool#7]
Hi there and thanks for this fork. I would like to package this in conda-forge (and maybe others). Would you consider giving this fork a new name that's different from "atool"?

**Comment by solsticedhiver** [comment]
hi.

It's just a fork, with a few commit, for now.

I don't want to be rude, but that's not my problem. Can't you give it another name for conda-forge, like atool-fork, atool-solstice, atool-sh or whatever ?

Also, I am not good at naming things, and finding a name for it is... complicated.

**Comment by jonashaag** [comment]
Sure but I wonder if we should put in an effort to make an "official" new version of atool. The original atool has been abandoned 10 years ago. So I was thinking if we should make an official "atool2" that we maintain and get into package managers.

**Comment by solsticedhiver** [comment]
I am not a proper maintainer either. Well, if you really want to, I could rename it.

**Comment by solsticedhiver** [comment]
done
